from pathlib import Path

FILE = Path("app/bot/routers/main_menu/renew_service_handler.py")
s = FILE.read_text(encoding="utf-8")

# This patch deliberately resolves renewal data from the callback's persistent
# identifiers instead of treating FSM/Redis state as the source of truth.
# It also accepts subscriptions whose persisted plan_id is stale/missing by
# using the existing _original_plan() recovery chain.

needle = '''    return None\n\n\n@router.callback_query(F.data == ENTRY_CALLBACK)\n'''
helper = '''    return None\n\n\nasync def _resolve_renewal_payment_data(\n    session: AsyncSession,\n    user: User,\n    subscription_id: int,\n    plan_id: int,\n    services: ServicesContainer,\n) -> tuple[Subscription, ServicePurchasePlan, SubscriptionData] | None:\n    """Resolve renewal payment data from persistent identifiers.\n\n    FSM/Redis is not used as the source of truth. The subscription is loaded\n    for the current user, the original plan is recovered through the existing\n    safe fallback chain, and the callback plan id must match that resolved\n    original plan. A fresh SubscriptionData is then rebuilt with the current\n    customer discount.\n    """\n    subscription = await _get_subscription(session, user, subscription_id, services)\n    if subscription is None:\n        return None\n\n    plan = await _original_plan(session, subscription)\n    if plan is None or plan.id != plan_id:\n        logger.warning(\n            "Renewal payment plan mismatch: subscription=%s persisted_plan=%s "\n            "callback_plan=%s resolved_plan=%s",\n            subscription.id,\n            subscription.plan_id,\n            plan_id,\n            plan.id if plan else None,\n        )\n        return None\n\n    data = await _subscription_data(session, subscription, plan, user)\n    return subscription, plan, data\n\n\n@router.callback_query(F.data == ENTRY_CALLBACK)\n'''
if s.count(needle) != 1:
    raise SystemExit("helper insertion point not found")
s = s.replace(needle, helper, 1)

# Replace the payment-method handler's FSM validation block with a DB-backed
# resolver. Keep the existing UI/state write because later card-receipt flow
# still needs the serialized SubscriptionData, but it is now derived fresh.
old = '''    packed = (await state.get_data()).get("subscription_data")\n    if not packed:\n        await callback.answer("❌ اطلاعات سفارش تمدید منقضی شده است.", show_alert=True)\n        await state.clear()\n        return\n\n    try:\n        data = SubscriptionData.deserialize(packed)\n    except Exception:\n        await callback.answer("❌ اطلاعات سفارش تمدید نامعتبر است.", show_alert=True)\n        await state.clear()\n        return\n\n    if data.user_id != user.tg_id or data.subscription_id != subscription_id or data.plan_id != plan_id:\n        await callback.answer("❌ اطلاعات سفارش با این کاربر یا سرویس مطابقت ندارد.", show_alert=True)\n        await state.clear()\n        return\n\n    subscription = await _get_subscription(session, user, subscription_id, services)\n    plan = await ServicePurchasePlan.get(session, plan_id)\n    if subscription is None or plan is None or plan.volume_gb <= 0 or plan.duration_days <= 0:\n        await callback.answer("❌ سرویس یا پلن تمدید دیگر معتبر نیست.", show_alert=True)\n        await state.clear()\n        return\n\n    if plan.id != subscription.plan_id:\n        original_plan = await _original_plan(session, subscription)\n        if original_plan is None or original_plan.id != plan.id:\n            await callback.answer("❌ پلن اصلی سرویس تغییر کرده است؛ سفارش تمدید را دوباره بسازید.", show_alert=True)\n            await state.clear()\n            return\n\n    data.duration = plan.duration_days\n    data.volume_gb = plan.volume_gb\n    customer_level, purchase_count, discounted_price = await get_discounted_plan_price(\n        session,\n        user.tg_id,\n        plan.price_toman,\n    )\n    data.price = discounted_price\n    data.original_price = plan.price_toman\n    data.discount_percent = int(\n        getattr(customer_level, "discount_percent", 0) or 0\n    )\n    data.discount_level_title = str(\n        getattr(customer_level, "title", "")\n        or getattr(customer_level, "name", "")\n        or ""\n    )\n    data.devices = subscription.devices\n    data.config_name = subscription.config_name\n    data.subscription_id = subscription.id\n    await state.update_data(subscription_data=data.serialize())\n'''
new = '''    resolved = await _resolve_renewal_payment_data(\n        session, user, subscription_id, plan_id, services\n    )\n    if resolved is None:\n        await callback.answer("❌ سرویس یا پلن اصلی دیگر معتبر نیست.", show_alert=True)\n        return\n\n    subscription, plan, data = resolved\n    await state.update_data(subscription_data=data.serialize())\n'''
if s.count(old) != 1:
    raise SystemExit("payment_methods block not found")
s = s.replace(old, new, 1)

# Replace gateway FSM/state validation with the same persistent resolver.
old_start = '''    current_state = await state.get_data()\n    logger.warning("GATEWAY DEBUG FULL STATE=%s", current_state)\n\n    packed = current_state.get("subscription_data")\n    logger.warning("GATEWAY DEBUG PACKED=%s", packed)\n\n    try:\n        data = SubscriptionData.deserialize(packed or "")\n    except Exception:\n        await callback.answer("❌ اطلاعات سفارش تمدید منقضی یا نامعتبر است.", show_alert=True)\n        await state.clear()\n        return\n\n    if data.user_id != user.tg_id or data.subscription_id != subscription_id or data.plan_id != plan_id:\n        await callback.answer("❌ اطلاعات سفارش با این کاربر یا سرویس مطابقت ندارد.", show_alert=True)\n        await state.clear()\n        return\n\n    subscription = await _get_subscription(session, user, subscription_id, services)\n    plan = await ServicePurchasePlan.get(session, plan_id)\n    if subscription is None or plan is None or plan.id != subscription.plan_id:\n        await callback.answer("❌ سرویس یا پلن اصلی دیگر معتبر نیست.", show_alert=True)\n        await state.clear()\n        return\n\n    data.duration = plan.duration_days\n    data.volume_gb = plan.volume_gb\n    customer_level, purchase_count, discounted_price = await get_discounted_plan_price(\n        session,\n        user.tg_id,\n        plan.price_toman,\n    )\n    data.price = discounted_price\n    data.original_price = plan.price_toman\n    data.discount_percent = int(\n        getattr(customer_level, "discount_percent", 0) or 0\n    )\n    data.discount_level_title = str(\n        getattr(customer_level, "title", "")\n        or getattr(customer_level, "name", "")\n        or ""\n    )\n    data.devices = subscription.devices\n    data.config_name = subscription.config_name\n    data.subscription_id = subscription.id\n    await state.update_data(subscription_data=data.serialize())\n'''
new_start = '''    resolved = await _resolve_renewal_payment_data(\n        session, user, subscription_id, plan_id, services\n    )\n    if resolved is None:\n        await callback.answer("❌ سرویس یا پلن اصلی دیگر معتبر نیست.", show_alert=True)\n        return\n\n    subscription, plan, data = resolved\n    # Keep a fresh copy for any downstream callback that still needs FSM\n    # context, but never require that old state to create the payment.\n    await state.update_data(subscription_data=data.serialize())\n'''
if s.count(old_start) != 1:
    raise SystemExit("gateway block not found")
s = s.replace(old_start, new_start, 1)

# Replace card FSM validation with the same resolver. The resulting fresh
# SubscriptionData is stored so custom_service_card_payment can continue the
# receipt UX without relying on stale renewal state.
old_card = '''    packed = (await state.get_data()).get("subscription_data")\n    try:\n        data = SubscriptionData.deserialize(packed or "")\n    except Exception:\n        await callback.answer("❌ اطلاعات سفارش تمدید منقضی یا نامعتبر است.", show_alert=True)\n        await state.clear()\n        return\n\n    if data.user_id != user.tg_id or data.subscription_id != subscription_id or data.plan_id != plan_id:\n        await callback.answer("❌ اطلاعات سفارش با این کاربر یا سرویس مطابقت ندارد.", show_alert=True)\n        await state.clear()\n        return\n\n    subscription = await _get_subscription(session, user, subscription_id, services)\n    plan = await ServicePurchasePlan.get(session, plan_id)\n    if subscription is None or plan is None or plan.id != subscription.plan_id:\n        await callback.answer("❌ سرویس یا پلن اصلی دیگر معتبر نیست.", show_alert=True)\n        await state.clear()\n        return\n\n    data.duration = plan.duration_days\n    data.volume_gb = plan.volume_gb\n    customer_level, purchase_count, discounted_price = await get_discounted_plan_price(\n        session,\n        user.tg_id,\n        plan.price_toman,\n    )\n    data.price = discounted_price\n    data.original_price = plan.price_toman\n    data.discount_percent = int(\n        getattr(customer_level, "discount_percent", 0) or 0\n    )\n    data.discount_level_title = str(\n        getattr(customer_level, "title", "")\n        or getattr(customer_level, "name", "")\n        or ""\n    )\n    data.devices = subscription.devices\n    data.config_name = subscription.config_name\n    data.subscription_id = subscription.id\n    await state.update_data(subscription_data=data.serialize())\n'''
new_card = '''    resolved = await _resolve_renewal_payment_data(\n        session, user, subscription_id, plan_id, services\n    )\n    if resolved is None:\n        await callback.answer("❌ سرویس یا پلن اصلی دیگر معتبر نیست.", show_alert=True)\n        return\n\n    subscription, plan, data = resolved\n    await state.update_data(subscription_data=data.serialize())\n'''
if s.count(old_card) != 1:
    raise SystemExit("card block not found")
s = s.replace(old_card, new_card, 1)

FILE.write_text(s, encoding="utf-8")
print(f"patched: {FILE}")
