from pathlib import Path

FILE = Path("app/bot/routers/main_menu/renew_service_handler.py")
s = FILE.read_text(encoding="utf-8")

# Renewal payment callbacks carry the persistent subscription/plan identifiers.
# They must be the source of truth; FSM/Redis is only a downstream transport
# for the card-receipt flow after the payment data has been freshly resolved.

# 1) Insert a single resolver immediately before the entry handler.
needle = '''    return None\n\n\n@router.callback_query(F.data == ENTRY_CALLBACK)\n'''
helper = '''    return None\n\n\nasync def _resolve_renewal_payment_data(\n    session: AsyncSession,\n    user: User,\n    subscription_id: int,\n    plan_id: int,\n    services: ServicesContainer,\n) -> tuple[Subscription, ServicePurchasePlan, SubscriptionData] | None:\n    """Resolve renewal payment data from persistent identifiers.\n\n    FSM/Redis is deliberately not used as the source of truth. The subscription\n    is loaded for the current user, its original plan is recovered through the\n    existing fallback chain, and the callback plan id must match that resolved\n    plan. A fresh SubscriptionData is then rebuilt with the current discount.\n    """\n    subscription = await _get_subscription(\n        session, user, subscription_id, services\n    )\n    if subscription is None:\n        return None\n\n    plan = await _original_plan(session, subscription)\n    if plan is None or plan.id != plan_id:\n        logger.warning(\n            "Renewal payment plan mismatch: subscription=%s persisted_plan=%s "\n            "callback_plan=%s resolved_plan=%s",\n            subscription.id,\n            subscription.plan_id,\n            plan_id,\n            plan.id if plan else None,\n        )\n        return None\n\n    data = await _subscription_data(session, subscription, plan, user)\n    return subscription, plan, data\n\n\n@router.callback_query(F.data == ENTRY_CALLBACK)\n'''
if s.count(needle) != 1:
    raise SystemExit("ERROR: helper insertion point not found")
s = s.replace(needle, helper, 1)

# 2) payment_methods: never require an old FSM snapshot.
old = '''    packed = (await state.get_data()).get("subscription_data")\n    if not packed:\n        await callback.answer("❌ اطلاعات سفارش تمدید منقضی شده است.", show_alert=True)\n        await state.clear()\n        return\n\n    try:\n        data = SubscriptionData.deserialize(packed)\n    except Exception:\n        await callback.answer("❌ اطلاعات سفارش تمدید نامعتبر است.", show_alert=True)\n        await state.clear()\n        return\n\n    if data.user_id != user.tg_id or data.subscription_id != subscription_id or data.plan_id != plan_id:\n        await callback.answer("❌ اطلاعات سفارش با این کاربر یا سرویس مطابقت ندارد.", show_alert=True)\n        await state.clear()\n        return\n\n    subscription = await _get_subscription(session, user, subscription_id, services)\n    plan = await ServicePurchasePlan.get(session, plan_id)\n    if subscription is None or plan is None or plan.volume_gb <= 0 or plan.duration_days <= 0:\n        await callback.answer("❌ سرویس یا پلن تمدید دیگر معتبر نیست.", show_alert=True)\n        await state.clear()\n        return\n\n    if plan.id != subscription.plan_id:\n        original_plan = await _original_plan(session, subscription)\n        if original_plan is None or original_plan.id != plan.id:\n            await callback.answer("❌ پلن اصلی سرویس تغییر کرده است؛ سفارش تمدید را دوباره بسازید.", show_alert=True)\n            await state.clear()\n            return\n\n    data.duration = plan.duration_days\n    data.volume_gb = plan.volume_gb\n    customer_level, purchase_count, discounted_price = await get_discounted_plan_price(\n        session,\n        user.tg_id,\n        plan.price_toman,\n    )\n    data.price = discounted_price\n    data.original_price = plan.price_toman\n    data.discount_percent = int(\n        getattr(customer_level, "discount_percent", 0) or 0\n    )\n    data.discount_level_title = str(\n        getattr(customer_level, "title", "")\n        or getattr(customer_level, "name", "")\n        or ""\n    )\n    data.devices = subscription.devices\n    data.config_name = subscription.config_name\n    data.subscription_id = subscription.id\n    await state.update_data(subscription_data=data.serialize())\n'''
new = '''    resolved = await _resolve_renewal_payment_data(\n        session, user, subscription_id, plan_id, services\n    )\n    if resolved is None:\n        await callback.answer("❌ سرویس یا پلن اصلی دیگر معتبر نیست.", show_alert=True)\n        return\n\n    subscription, plan, data = resolved\n    await state.update_data(subscription_data=data.serialize())\n'''
if s.count(old) != 1:
    raise SystemExit("ERROR: payment_methods block not found")
s = s.replace(old, new, 1)

# 3) gateway_payment: same resolver, no stale FSM dependency.
old_gateway = '''    current_state = await state.get_data()\n    logger.warning("GATEWAY DEBUG FULL STATE=%s", current_state)\n\n    packed = current_state.get("subscription_data")\n    logger.warning("GATEWAY DEBUG PACKED=%s", packed)\n\n    try:\n        data = SubscriptionData.deserialize(packed or "")\n    except Exception:\n        await callback.answer("❌ اطلاعات سفارش تمدید منقضی یا نامعتبر است.", show_alert=True)\n        await state.clear()\n        return\n\n    if data.user_id != user.tg_id or data.subscription_id != subscription_id or data.plan_id != plan_id:\n        await callback.answer("❌ اطلاعات سفارش با این کاربر یا سرویس مطابقت ندارد.", show_alert=True)\n        await state.clear()\n        return\n\n    subscription = await _get_subscription(session, user, subscription_id, services)\n    plan = await ServicePurchasePlan.get(session, plan_id)\n    if subscription is None or plan is None or plan.id != subscription.plan_id:\n        await callback.answer("❌ سرویس یا پلن اصلی دیگر معتبر نیست.", show_alert=True)\n        await state.clear()\n        return\n\n    data.duration = plan.duration_days\n    data.volume_gb = plan.volume_gb\n    customer_level, purchase_count, discounted_price = await get_discounted_plan_price(\n        session,\n        user.tg_id,\n        plan.price_toman,\n    )\n    data.price = discounted_price\n    data.original_price = plan.price_toman\n    data.discount_percent = int(\n        getattr(customer_level, "discount_percent", 0) or 0\n    )\n    data.discount_level_title = str(\n        getattr(customer_level, "title", "")\n        or getattr(customer_level, "name", "")\n        or ""\n    )\n    data.devices = subscription.devices\n    data.config_name = subscription.config_name\n    data.subscription_id = subscription.id\n    await state.update_data(subscription_data=data.serialize())\n'''
new_gateway = '''    resolved = await _resolve_renewal_payment_data(\n        session, user, subscription_id, plan_id, services\n    )\n    if resolved is None:\n        await callback.answer("❌ سرویس یا پلن اصلی دیگر معتبر نیست.", show_alert=True)\n        return\n\n    subscription, plan, data = resolved\n    await state.update_data(subscription_data=data.serialize())\n'''
if s.count(old_gateway) != 1:
    raise SystemExit("ERROR: gateway block not found")
s = s.replace(old_gateway, new_gateway, 1)

# 4) card_payment: same resolver; then store fresh data for the existing
# custom_service_card_payment receipt handler.
old_card = '''    packed = (await state.get_data()).get("subscription_data")\n    try:\n        data = SubscriptionData.deserialize(packed or "")\n    except Exception:\n        await callback.answer("❌ اطلاعات سفارش تمدید منقضی یا نامعتبر است.", show_alert=True)\n        await state.clear()\n        return\n\n    if data.user_id != user.tg_id or data.subscription_id != subscription_id or data.plan_id != plan_id:\n        await callback.answer("❌ اطلاعات سفارش با این کاربر یا سرویس مطابقت ندارد.", show_alert=True)\n        await state.clear()\n        return\n\n    subscription = await _get_subscription(session, user, subscription_id, services)\n    plan = await ServicePurchasePlan.get(session, plan_id)\n    if subscription is None or plan is None or plan.id != subscription.plan_id:\n        await callback.answer("❌ سرویس یا پلن اصلی دیگر معتبر نیست.", show_alert=True)\n        await state.clear()\n        return\n\n    data.duration = plan.duration_days\n    data.volume_gb = plan.volume_gb\n    customer_level, purchase_count, discounted_price = await get_discounted_plan_price(\n        session,\n        user.tg_id,\n        plan.price_toman,\n    )\n    data.price = discounted_price\n    data.original_price = plan.price_toman\n    data.discount_percent = int(\n        getattr(customer_level, "discount_percent", 0) or 0\n    )\n    data.discount_level_title = str(\n        getattr(customer_level, "title", "")\n        or getattr(customer_level, "name", "")\n        or ""\n    )\n    data.devices = subscription.devices\n    data.config_name = subscription.config_name\n    data.subscription_id = subscription.id\n    await state.update_data(subscription_data=data.serialize())\n'''
new_card = '''    resolved = await _resolve_renewal_payment_data(\n        session, user, subscription_id, plan_id, services\n    )\n    if resolved is None:\n        await callback.answer("❌ سرویس یا پلن اصلی دیگر معتبر نیست.", show_alert=True)\n        return\n\n    subscription, plan, data = resolved\n    await state.update_data(subscription_data=data.serialize())\n'''
if s.count(old_card) != 1:
    raise SystemExit("ERROR: card block not found")
s = s.replace(old_card, new_card, 1)

FILE.write_text(s, encoding="utf-8")
print(f"PATCH OK: {FILE}")
