
class NavDownload(str, Enum):
    MAIN = "download"
    PLATFORM = "platform"
    PLATFORM_IOS = f"{PLATFORM}_ios"
    PLATFORM_ANDROID = f"{PLATFORM}_android"
    PLATFORM_WINDOWS = f"{PLATFORM}_windows"


class NavSubscription(str, Enum):
    MAIN = "subscription"
    BUY = "buy"
    RENEW_SERVICE = "renew_service"
    CHANGE = "change"
    EXTEND = "extend"
    PROCESS = "process"
    DEVICES = "devices"
    DURATION = "duration"
    PLAN_ONE_MONTH = "plan_one_month"
    PLAN_THREE_MONTH = "plan_three_month"
    PLAN = "plan"
    PROMOCODE = "promocode"
    GET_TRIAL = "get_trial"
    PAY = "pay"
    PAY_YOOKASSA = f"{PAY}_yookassa"
    PAY_TELEGRAM_STARS = f"{PAY}_telegram_stars"
    PAY_CRYPTOMUS = f"{PAY}_cryptomus"
    PAY_HELEKET = f"{PAY}_heleket"
    PAY_YOOMONEY = f"{PAY}_yoomoney"
    BACK_TO_DURATION = "back_to_duration"
    BACK_TO_PAYMENT = "back_to_payment"
