from enum import Enum


class NavMain(str, Enum):
    START = "start"
    MAIN_MENU = "main_menu"
    CLOSE_NOTIFICATION = "close_notification"
    REDIRECT_TO_DOWNLOAD = "redirect_to_download"
    LANGUAGE = "language"
    CUSTOM_SERVICE = "custom_service"
    MY_SERVICES = "my_services"
    WALLET = "wallet"
    CUSTOMER_LEVEL = "customer_level"


class NavProfile(str, Enum):
    MAIN = "profile"
    SHOW_KEY = "show_key"


class NavReferral(str, Enum):
    MAIN = "referral"
    GET_REFERRED_TRIAL = "get_referral_trial"


class NavSupport(str, Enum):
    MAIN = "support"
    TRAINING = "support:training"
    TRAINING_HAPP = "support:training:happ"
    TRAINING_V2RAY = "support:training:v2ray"
    TRAINING_V2BOX = "support:training:v2box"
    TRAINING_APP_PLATFORM = "support:training:app"
    CONTACT = "support:contact"
    SEND_MESSAGE = "support:contact:send"
    MY_TICKETS = "support:contact:tickets"
    TICKET_VIEW = "support:ticket:view"
    TICKET_CONVERSATION = "support:ticket:conversation"
    TICKET_REPLY = "support:ticket:reply"
    TICKET_CLOSE = "support:ticket:close"


class NavDownload(str, Enum):
    MAIN = "download"
    PLATFORM = "platform"
    PLATFORM_IOS = f"{PLATFORM}_ios"
    PLATFORM_ANDROID = f"{PLATFORM}_android"
    PLATFORM_WINDOWS = f"{PLATFORM}_windows"


class NavSubscription(str, Enum):
    MAIN = "subscription"
    BUY = "buy"
    RENEW_SERVICE = "renew_service"
    ADD_TRAFFIC = "add_traffic"
    CHANGE = "change"
    EXTEND = "extend"
    PROCESS = "process"
    DEVICES = "devices"
    DURATION = "duration"
    PLAN_ONE_MONTH = "plan_one_month"
    PLAN_THREE_MONTH = "plan_three_month"
    PLAN = "plan"
    CONFIG_NAME = "config_name"
    PROMOCODE = "promocode"
    GIFT_CODE = "gift_code"
    GET_TRIAL = "get_trial"
    PAY = "pay"
    PAY_ZARINPAL = f"{PAY}_zarinpal"
    BACK_TO_DURATION = "back_to_duration"
    BACK_TO_PAYMENT = "back_to_payment"


class NavAdminTools(str, Enum):
    MAIN = "admin_tools"
    TEST_ACCOUNT_SETTINGS = "test_account_settings"
    SERVER_MANAGEMENT = "server_management"
    INBOUND_MANAGEMENT = "inbound_management"
    SHOW_SERVER = "show_server"
    PING_SERVER = "ping_server"
    ADD_SERVER = "add_server"
    ADD_SERVER_BACK = "add_server_back"
    СONFIRM_ADD_SERVER = "сonfirm_add_server"
    DELETE_SERVER = "delete_server"
    EDIT_SERVER = "edit_server"
    EDIT_SERVER_BACK = "edit_server_back"
    CONFIRM_EDIT_SERVER = "confirm_edit_server"
    SYNC_SERVERS = "sync_servers"
    STATISTICS = "statistics"
    USER_EDITOR = "user_editor"
    INVITE_EDITOR = "invite_editor"
    CREATE_INVITE = "create_invite"
    DELETE_INVITE = "delete_invite"
    EDIT_INVITE = "edit_invite"
    LIST_INVITES = "list_invites"
    SHOW_INVITE_PAGE = "show_invite_page"
    SHOW_INVITE_DETAILS = "show_invite_details"
    TOGGLE_INVITE_STATUS = "toggle_invite_status"
    CONFIRM_DELETE_INVITE = "confirm_delete_invite"
    PROMOCODE_EDITOR = "promocode_editor"
    GIFT_REPORTS = "gift_reports"
    CREATE_PROMOCODE = "create_promocode"
    CREATE_AND_SEND_PROMOCODE_USER = "create_and_send_promocode_user"
    CREATE_AND_SEND_PROMOCODE_ALL = "create_and_send_promocode_all"
    DELETE_PROMOCODE = "delete_promocode"
    EDIT_PROMOCODE = "edit_promocode"
    NOTIFICATION = "notification"
    SEND_NOTIFICATION_USER = "send_notification_user"
    SEND_NOTIFICATION_ALL = "send_notification_all"
    CONFIRM_SEND_NOTIFICATION = "confirm_send_notification"
    LAST_NOTIFICATION = "last_notification"
    EDIT_NOTIFICATION = "edit_notification"
    DELETE_NOTIFICATION = "delete_notification"
    CREATE_BACKUP = "create_backup"
    MAINTENANCE_MODE = "maintenance_mode"
    MAINTENANCE_MODE_ENABLE = "maintenance_mode_enable"
    MAINTENANCE_MODE_DISABLE = "maintenance_mode_disable"
    RESTART_BOT = "restart_bot"
    CARD_SETTINGS = "card_settings"
    PAYMENT_GATEWAY_SETTINGS = "payment_gateway_settings"
    ENV_SETTINGS = "env_settings"
    CUSTOM_SERVICE_PRICING = "custom_service_pricing"
    SERVICE_PURCHASE_MANAGEMENT = "service_purchase_management"
    SERVICE_PURCHASE_ONE_MONTH = "service_purchase_one_month"
    SERVICE_PURCHASE_THREE_MONTH = "service_purchase_three_month"
    SERVICE_PURCHASE_DEVICES = "service_purchase_devices"
    SERVICE_PURCHASE_PLAN = "service_purchase_plan"
    SERVICE_PURCHASE_CREATE_ONE_MONTH = "service_purchase_create_one_month"
    SERVICE_PURCHASE_CREATE_THREE_MONTH = "service_purchase_create_three_month"
    SERVICE_PURCHASE_EDIT = "service_purchase_edit"
    SERVICE_PURCHASE_DELETE = "service_purchase_delete"
    SUBSCRIPTION_SETTINGS = "subscription_settings"
    CUSTOMER_LEVEL_SETTINGS = "customer_level_settings"
    REFERRAL_SETTINGS = "referral_settings"
    WELCOME_MESSAGE_SETTINGS = "welcome_message_settings"
