from __future__ import annotations

import logging
import uuid
from decimal import Decimal, InvalidOperation

from aiohttp import ClientSession, ClientTimeout
from aiohttp.web import Application, Request, Response
from aiogram import Bot
from aiogram.fsm.storage.redis import RedisStorage
from aiogram.utils.i18n import I18n
from sqlalchemy.ext.asyncio import async_sessionmaker

from app.bot.models import ServicesContainer, SubscriptionData
from app.bot.payment_gateways._gateway import PaymentGateway
from app.bot.utils.constants import Currency, TransactionStatus
from app.config import Config
from app.db.models import PaymentGatewaySettings, Transaction

logger = logging.getLogger(__name__)


class KPay(PaymentGateway):
    """KPay card-to-card hosted checkout integration.

    KPay owns the bank cards. ToonelVPN never stores full card numbers.

    KPay's documented Bearer credential is the account access token returned
    by /auth/login or /auth/register. Shop/card UUIDs are generated by KPay
    and are automatically discovered through /shops and /cards.
    """

    name = "💳 کارت‌به‌کارت هوشمند"
    currency = Currency.TOMAN
    callback = "pay_kpay"
    CALLBACK_PATH = "/kpay/callback"
    API_BASE_URL = "https://kpay.website/api/v1"
    wallet_reference_prefix = "kpay"

    def __init__(self, app: Application, config: Config, session: async_sessionmaker, storage: RedisStorage, bot: Bot, i18n: I18n, services: ServicesContainer) -> None:
        self.app = app
        self.config = config
        self.session = session
        self.storage = storage
        self.bot = bot
        self.i18n = i18n
        self.services = services
        self.app.router.add_get(self.CALLBACK_PATH, self.callback_handler)
        self.app.router.add_post(self.CALLBACK_PATH, self.callback_handler)
        logger.info("KPay payment gateway initialized.")

    async def _get_credentials(self) -> tuple[str | None, str | None, str | None]:
        async with self.session() as session:
            settings = await PaymentGatewaySettings.get(session)
            if settings is None:
                return None, None, None
            # Legacy DB column name is kept for migration compatibility, but
            # its value is now the KPay account access token, not the Shop API key.
            return (
                settings.kpay_api_key.strip() or None,
                settings.kpay_shop_id.strip() or None,
                settings.kpay_card_id.strip() or None,
            )

    async def _save_resource_ids(self, shop_id: str, card_id: str) -> None:
        async with self.session() as session:
            settings = await PaymentGatewaySettings.get(session)
            if settings is None:
                settings = PaymentGatewaySettings(id=1)
                session.add(settings)
            settings.kpay_shop_id = shop_id
            settings.kpay_card_id = card_id
            await session.commit()

    async def _request(self, method: str, path: str, access_token: str, payload: dict | None = None) -> dict:
        timeout = ClientTimeout(total=20)
        headers = {
            "Authorization": f"Bearer {access_token}",
            "Content-Type": "application/json",
            "Accept": "application/json",
        }
        async with ClientSession(timeout=timeout) as client:
            async with client.request(method, f"{self.API_BASE_URL}{path}", json=payload, headers=headers) as response:
                body = await response.json(content_type=None)
                if response.status >= 400:
                    raise RuntimeError(f"KPay HTTP {response.status}: {body}")
                if not isinstance(body, dict):
                    raise RuntimeError(f"Unexpected KPay response: {body}")
                return body

    async def sync_resources(self) -> dict:
        """Fetch active Shop/Card UUIDs from KPay and cache them locally."""
        access_token, saved_shop_id, saved_card_id = await self._get_credentials()
        if not access_token:
            raise RuntimeError("Access Token حساب KPay تنظیم نشده است")

        shops_response = await self._request("GET", "/shops", access_token)
        cards_response = await self._request("GET", "/cards", access_token)
        shops = shops_response.get("shops") or []
        cards = cards_response.get("cards") or []

        active_shops = [item for item in shops if item.get("id") and item.get("is_active") is not False]
        active_cards = [item for item in cards if item.get("id") and item.get("is_active") is not False]
        if not active_shops:
            raise RuntimeError("هیچ Shop فعالی در حساب KPay پیدا نشد")
        if not active_cards:
            raise RuntimeError("هیچ Card فعالی در حساب KPay پیدا نشد")

        shop = next((item for item in active_shops if str(item.get("id")) == saved_shop_id), active_shops[0])
        card = next((item for item in active_cards if str(item.get("id")) == saved_card_id), active_cards[0])
        shop_id = str(shop["id"])
        card_id = str(card["id"])
        await self._save_resource_ids(shop_id, card_id)

        return {"shop": shop, "card": card, "callback_url": f"{self.config.bot.DOMAIN.rstrip('/')}{self.CALLBACK_PATH}"}

    @staticmethod
    def _validate_toman(amount: int | float | str) -> int:
        try:
            value = Decimal(str(amount))
        except (InvalidOperation, ValueError) as exc:
            raise ValueError(f"Invalid Toman amount: {amount}") from exc
        if value <= 0 or value != value.to_integral_value():
            raise ValueError("KPay amount must be a positive whole Toman value")
        return int(value)

    @staticmethod
    def _extract_authority(request: Request) -> str:
        for key in ("authority", "Authority", "payment_id", "transaction_id", "id"):
            value = request.query.get(key)
            if value and str(value).strip():
                return str(value).strip()
        return ""

    async def create_payment(self, data: SubscriptionData) -> str:
        if data.payment_kind not in {"subscription", "wallet_topup"}:
            raise RuntimeError(f"KPay is not supported for payment kind: {data.payment_kind}")
        access_token, shop_id, card_id = await self._get_credentials()
        if not access_token:
            raise RuntimeError("Access Token حساب KPay تنظیم نشده است")

        # Shop/Card IDs are KPay-generated UUIDs. Refresh them automatically
        # before creating a transaction so stale/deleted IDs are repaired.
        resources = await self.sync_resources()
        shop_id = str(resources["shop"].get("id") or shop_id or "")
        card_id = str(resources["card"].get("id") or card_id or "")
        if not shop_id or not card_id:
            raise RuntimeError("KPay Shop/Card فعال پیدا نشد")

        amount_toman = self._validate_toman(data.price)
        amount_rial = amount_toman * 10
        payment_id = f"toonel-kpay-{uuid.uuid4().hex}"
        callback_url = f"{self.config.bot.DOMAIN.rstrip('/')}{self.CALLBACK_PATH}"
        response = await self._request(
            "POST", "/transactions/create", access_token,
            {
                "shop_id": shop_id,
                "card_id": card_id,
                "amount": amount_rial,
                "callback_url": callback_url,
                "description": f"ToonelVPN payment {payment_id}",
                "factor_number": payment_id,
                "fee_side": "customer",
            },
        )
        authority = str(response.get("authority") or "").strip()
        payment_url = str(response.get("payment_url") or "").strip()
        remote_amount = response.get("amount")
        if not authority or not payment_url:
            raise RuntimeError(f"KPay response has no authority/payment_url: {response}")
        if remote_amount is not None and int(Decimal(str(remote_amount))) != amount_rial:
            raise RuntimeError(f"KPay amount mismatch while creating payment: expected={amount_rial} got={remote_amount}")

        async with self.session() as session:
            transaction = await Transaction.create(
                session=session,
                tg_id=data.user_id,
                subscription=data.serialize(),
                payment_id=authority,
                status=TransactionStatus.PENDING,
            )
            if transaction is None:
                raise RuntimeError(f"Could not create KPay transaction {authority}")
        logger.info("KPay payment created: user=%s authority=%s expected_rials=%s", data.user_id, authority, amount_rial)
        return payment_url

    async def _verify_remote_payment(self, authority: str, expected_rials: int) -> bool:
        access_token, _, _ = await self._get_credentials()
        if not access_token:
            raise RuntimeError("Access Token حساب KPay تنظیم نشده است")

        check = await self._request("GET", f"/transactions/check/{authority}", access_token)
        check_status = str(check.get("status") or "").lower()
        check_paid = bool(check.get("is_paid")) or check_status in {"paid", "completed", "success", "successful", "verified", "confirmed"}
        if not check_paid:
            return False

        response = await self._request("POST", "/transactions/verify", access_token, {"authority": authority})
        status = str(response.get("status") or "").lower()
        paid = bool(response.get("is_paid")) or status in {"paid", "completed", "success", "successful", "verified", "confirmed"}
        amount = response.get("amount")
        if amount is not None:
            try:
                verified_rials = int(Decimal(str(amount)))
            except (InvalidOperation, ValueError):
                raise RuntimeError(f"KPay returned invalid verified amount: {amount}")
            if verified_rials != expected_rials:
                raise RuntimeError(f"KPay amount mismatch: expected={expected_rials} got={verified_rials} authority={authority}")
        return paid

    async def handle_payment_succeeded(self, payment_id: str) -> None:
        lock = self.storage.redis.lock(f"payment:kpay:{payment_id}", timeout=300, blocking_timeout=10)
        async with lock:
            async with self.session() as session:
                transaction = await Transaction.get_by_id(session=session, payment_id=payment_id)
                if transaction is None:
                    raise RuntimeError(f"KPay transaction {payment_id} was not found")
                if transaction.status == TransactionStatus.COMPLETED:
                    logger.info("Ignoring duplicate KPay success for %s", payment_id)
                    return
                if transaction.status == TransactionStatus.CANCELED:
                    logger.warning("Ignoring success for canceled KPay transaction %s", payment_id)
                    return
                data = SubscriptionData.deserialize(transaction.subscription)
            expected_rials = self._validate_toman(data.price) * 10
            paid = await self._verify_remote_payment(payment_id, expected_rials)
            if not paid:
                logger.info("KPay callback arrived before payment confirmation: %s", payment_id)
                return
            await self._on_payment_succeeded(payment_id)

    async def handle_payment_canceled(self, payment_id: str) -> None:
        async with self.session() as session:
            transaction = await Transaction.get_by_id(session=session, payment_id=payment_id)
            if transaction is None:
                raise RuntimeError(f"KPay transaction {payment_id} was not found")
            if transaction.status == TransactionStatus.COMPLETED:
                logger.info("Ignoring cancellation for completed KPay transaction %s", payment_id)
                return
        await self._on_payment_canceled(payment_id)

    async def callback_handler(self, request: Request) -> Response:
        authority = self._extract_authority(request)
        if not authority:
            return Response(text="پرداخت نامشخص است؛ کد تراکنش دریافت نشد.", status=400, content_type="text/plain", charset="utf-8")
        try:
            await self.handle_payment_succeeded(authority)
        except RuntimeError as exc:
            logger.warning("KPay callback rejected: authority=%s error=%s", authority, exc)
            return Response(text=f"پرداخت قابل تأیید نیست.\n{str(exc)[:500]}", status=400, content_type="text/plain", charset="utf-8")
        except Exception:
            logger.exception("KPay callback processing failed: authority=%s", authority)
            return Response(text="خطا در تأیید پرداخت. لطفاً چند لحظه بعد وضعیت سرویس را بررسی کنید.", status=500, content_type="text/plain", charset="utf-8")
        return Response(text="پرداخت شما با موفقیت تأیید شد. پیام تحویل سرویس در تلگرام برای شما ارسال می‌شود.", status=200, content_type="text/plain", charset="utf-8")

    async def test_connection(self) -> dict:
        access_token, _, _ = await self._get_credentials()
        if not access_token:
            raise RuntimeError("Access Token حساب KPay تنظیم نشده است")
        return await self.sync_resources()
